import Footer from "./components/footer/footer";
import "./globals.css";

import { Providers } from "./store/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <head>
          <link rel="stylesheet" href="https://use.typekit.net/ufp0hxo.css" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C400%2C300%2C600%2C700"
          />
        </head>
        <body className={`font-main pt-10`}>
          {children}
          <Footer />
          <div>
            <label
              for="steps-range"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
            >
              Range steps
            </label>
            <input
              id="steps-range"
              type="range"
              min="0"
              max="200"
              step="1"
              class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700"
            />
          </div>
        </body>
      </html>
    </Providers>
  );
}
